### ISSUE TITLE
Project onderwerp/voorstel

### ISSUE THREAD

**Issue by YoussefBoudiba** [WIS7/weshare#2]
Gaan we voor de voorstel van Yannick: "bijhouden van het zien van bekende personen" ?

**Comment by clone1612** [comment]
Is natuurlijk een optie, maar hoe meer ik er over denk hoe meer het lijkt dat het best wat als een soort van stalking overkomt =P Mijn voorkeer ging dan uit naar eventueel concerten of zo bijhouden, maar bekende personen is ook goed voor mij (dan wel met een sarcastische naam of zo: "ClearlyNotStalking" of "SurelyTotallyNotStalking")

**Comment by YoussefBoudiba** [comment]
Een andere groep gaat al concerten doen. Uiteindelijk is de ufo-idee best wel origineel. Ik heb het met Roberto over gehad en hij is het met mij eens.

**Comment by clone1612** [comment]
Ok, sorry dat ik vandaag niet was ben namelijk ziek.

**Comment by YoussefBoudiba** [comment]
Gaan we dan voor de UFO? (bevestiging zodat ik de issue kan sluiten).

**Comment by clone1612** [comment]
Ja, indien jullie beiden akkoord zijn natuurlijk :)

**Comment by YoussefBoudiba** [comment]
UFO tracker it is :)
